language: python
sudo: false
dist: xenial
python:
  - "3.6"
  - "3.7"
install:
  - pip install tox
  - pip install tox-travis
  - pip install codecov
script: tox
after_success:
  - codecov -f .test_report/coverage.xml
